name: Build project with Maven
on:
  pull_request:
  push:
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Java setup
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run tests and install using Maven
      run: mvn -B clean install com.mycila:license-maven-plugin:check
